### ISSUE TITLE
Persona 5 issues

### ISSUE THREAD

**Issue by paula-utrilla-ts** [GoogleCloudPlatform/customer-experience-modernization#8]
Hi,

I'm in the branch genai-for-cxm trying to deploy the Persona 5 use case in my GCP project but I found several problems following the README file.

The first one is in the Firestore Setup, where are those files? because for example the file full_conversations is not in the repository, so the script doesn't work.

Also, in the creation of the Cloud Run, the Docker image is not working, when I try to create the resource I receive the error: The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable
Do I have to configure anything else that is not in the README file ?

Thanks,

**Comment by egonrian** [comment]
Hi @paula-utrilla-ts, thank you for following and testing the README file.

I transferred the issue to the new repo and put a migration note in the other repo.

I will improve the README file and the automation scripts this week.
